Solcuionando problemas agente clonador

diff --git a/JENKINSFILE_agentes b/JENKINSFILE_agentes
--- a/JENKINSFILE_agentes
+++ b/JENKINSFILE_agentes
@@ -19,7 +19,7 @@ pipeline {
                 sh 'whoami && hostname && pwd'
                 unstash 'workspace-clonado'
                 sh 'pip3 install --upgrade pip'
-                sh 'pip3 install flask pytest requests'
+                sh 'pip3 install flask pytest requests --break-system-packages'
                 echo 'Dependencias instaladas correctamente'
             }
         }
@@ -40,7 +40,6 @@ pipeline {
                 echo 'Iniciando Flask y Wiremock en agente-deploy...'
                 sh 'whoami && hostname && pwd'
                 unstash 'workspace-build'
-
                 sh '''
                    nohup python3 app/api.py --host=0.0.0.0 --port=5000 &
                    sleep 5
@@ -56,7 +55,7 @@ pipeline {
                    done
 
                    mkdir -p test/wiremock
-                   [ ! -f test/wiremock/wiremock-standalone-2.27.2.jar ] && echo "Descargando Wiremock JAR..." && curl -L https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.2.jar -o test/wiremock/wiremock-standalone-2.27.2.jar
+                   [ ! -f test/wiremock/wiremock-standalone-2.27.2.jar ] && echo "Descargando Wiremock JAR..." && curl -L https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone-2.27.2.jar -o test/wiremock/wiremock-standalone-2.27.2.jar
 
                    nohup java -jar test/wiremock/wiremock-standalone-2.27.2.jar --port 9090 --root-dir test/wiremock &
                    sleep 5
@@ -82,7 +81,7 @@ pipeline {
                         sh 'whoami && hostname && pwd'
                         unstash 'workspace-build'
                         echo 'Ejecutando tests unitarios...'
-                        sh 'python3 -m pytest test/unit --junitxml=result.xml || echo "Error en test unitario."'
+                        sh 'pytest test/unit --junitxml=result.xml || echo "Error en test unitario."'
                     }
                 }
 
@@ -104,7 +103,7 @@ pipeline {
                         done
                         '''
                         echo 'Ejecutando test de servicio...'
-                        sh 'python3 -m pytest test/rest --junitxml=results-service.xml || echo "Error en test de servicio."'
+                        sh 'pytest test/rest --junitxml=results-service.xml || echo "Error en test de servicio."'
                     }
                 }
             }
