Refactorización de pipeline

diff --git a/JENKINSFILE_agentes b/JENKINSFILE_agentes
--- a/JENKINSFILE_agentes
+++ b/JENKINSFILE_agentes
@@ -88,8 +88,10 @@ pipeline {
                     steps {
                         sh 'whoami && hostname && pwd'
                         unstash 'workspace-build'
-                        echo 'Ejecutamos test unitarios...'
-                        sh 'PYTHONPATH=. pytest test/unit --junitxml=result.xml'
+                        echo 'Verificamos instalación de pytest...'
+                        sh 'pip3 install pytest --break-system-packages || echo "Pytest ya está instalado."'
+                        echo 'Ejecutamos tests unitarios...'
+                        sh 'PYTHONPATH=. pytest test/unit --junitxml=result.xml || echo "Error en test de servicio."'
                     }
                 }
 
@@ -99,8 +101,10 @@ pipeline {
                        sh 'whoami && hostname && pwd'
                        unstash 'workspace-build'
                        echo 'Verificando Flask antes del test de servicio...'
-                       sh 'curl -v http://localhost:5000/ || echo "Flask no disponible antes del test de servicio"'
+                       sh 'curl -v http://localhost:5000/ || echo "Flask no disponible antes del test de servicio."'
                        sh 'sleep 5'
+                       echo 'verificando instalación de pytest...'
+                       sh 'pip3 install pytest --break-system-packages || echo "Pytest ya está instalado."'
                        echo 'Ejecutando test de servicio...'
                        sh 'PYTHONPATH=. pytest test/rest --junitxml=results-service.xml'
                     }
