Se agrega /opt/venv/bin/python3 para correguir error 403

diff --git a/JENKINSFILE_agentes b/JENKINSFILE_agentes
--- a/JENKINSFILE_agentes
+++ b/JENKINSFILE_agentes
@@ -58,12 +58,10 @@ pipeline {
                     steps {
                         unstash 'workspace-build'
                         sh 'whoami && hostname && pwd'
+                        
                         sh '''
-                            export PATH="/opt/venv/bin:$PATH"
                             export PYTHONPATH=$PYTHONPATH:$(pwd)
-                            
                             echo "Esperando que Flask esté disponible..."
-
                             for i in {1..10}; do
                             if curl -s http://localhost:5000/; then
                                 echo "Flask está disponible para tests"
@@ -73,9 +71,9 @@ pipeline {
                                 sleep 2
                             fi
                         done
+                         /opt/venv/bin/python3 -m pytest test/rest --junitxml=results-service.xml || echo "Error en test de servicio."
                         '''
-                        sh 'python3 -m pytest test/rest --junitxml=results-service.xml || echo "Error en test de servicio."'
-                    }
+            }
         }
     }
 
